name: Lint Backend

on:
  pull_request:
    branches: [main]
    paths: ['Backend/**']
    # paths:
    #   - 'Backend/'
      # - 'fea-backend/'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
      - run: ./mvnw checkstyle:check
        working-directory: Backend
