name: Lint Data

on:
  pull_request:
    branches: [main]
    paths: ['Data-analytics/**']  # Include all files inside the folder

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Data-analytics

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install linters
        run: pip install black flake8

      - name: Run Black (check format)
        run: black --check .

      - name: Run Flake8 (linting)
        run: flake8 .



# name: Lint Data

# on:
#   pull_request:
#     branches: [main]
#     paths: ['Data-analytics/']

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: Data-analytics

#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'
#       - run: pip install black flake8
#       - run: black --check .
#       - run: flake8 .
