name: Lint Data

on:
  pull_request:
    branches: [main]
    paths: ['Data-analytics/']

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Data-analytics

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install black flake8
      - run: black --check .
      - run: flake8 .
